### ISSUE TITLE
ui: collapsible - header margins

### ISSUE THREAD

**Issue by catlabs** [NationalBankBelgium/stark#731] opened 2018-09-28 13:51 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/NationalBankBelgium/stark/blob/master/CONTRIBUTING.md#got-a-question-or-problem
</code></pre>

## Current behavior
Currently the collapsible header has margin top and bottom and when we over the header only a part of it is highlighting.

## Expected behavior
Highlight should be on all the header

**Comment by christophercr** [comment] 2018-11-06 12:02
Closing this since the issue is no longer reproducible.

**Closed by christophercr** 2018-11-06 12:02 UTC
Labels: comp: stark-ui, must, status: obsolete, type: bug
