### ISSUE TITLE
Table column filter positioning 

### ISSUE THREAD

**Issue by mhenkens** [NationalBankBelgium/stark#3428] opened 2022-07-27 08:56 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/NationalBankBelgium/stark/blob/master/CONTRIBUTING.md#got-a-question-or-problem
</code></pre>

## Current behavior
On the table when define the filterPosition on the StarkTableFilter, this field do not change the position however if the property is set to the column definition then the filter position is changed

## Expected behavior
Apply the filterPosition when define in the filter level .

**Comment by SuperITMan** [comment] 2022-07-29 12:29
@mhenkens 

I'm not sure to understand the issue here 😕 
When defining the `filter` for the stark-table component, we define a `StarkTableFilter` object which contains some of the following properties:

```typescript
/**
 * Represents the column filtering options of the {@link StarkTableComponent}.
 */
export interface StarkTableFilter {
	// ...
	
	/**
	 * Array of {@link StarkTableColumnFilter} objects that define column filters
	 */
	columns?: StarkTableColumnFilter[];

	// ...

	/**
	 * The position in which the global filter box for the table should be displayed.
	 *
	 * Default: `"below"`
	 */
	filterPosition?: "above" | "below";
}
```

To define the filter position for the columns, we must define an array of `StarkTableColumnFilter` for the columns.
This interface contains, among other, the following property:

```typescript
/**
 * Definition of the filter in the {@link StarkTableComponent}
 */
export interface StarkTableColumnFilter {
	/**
	 * The position where the column filter box should be displayed.
	 *
	 * Default: `"below"`
	 */
	filterPosition?: "below" | "above";
}
```

According to the documentation, the `filterPosition` in the `StarkTableFilter` interface must impact **only** the global filter.

Changing this behavior as you suggest would be a change/feature and not a bug.

Could you check if this change is required or if we can close this issue ? 😊 

Alexis

**Comment by mhenkens** [comment] 2022-07-29 12:37
@SuperITMan 
When you define the filterPosition in columns level, it's working fine,

When you define the filterPosition in filter level, the filter always is always display below.

**Comment by SuperITMan** [comment] 2022-07-29 12:51
Indeed, it works as documented.
The `filterPosition` in filter level impacts only the global filter.
For the rest, the default position is `below`.

Changing this behavior as requested represents a breaking change.

**Closed** 2022-09-09 14:10 UTC
