### ISSUE TITLE
ui: datePicker - When using starkDateMask, the date is broken when edit it

### ISSUE THREAD

**Issue by SuperITMan** [NationalBankBelgium/stark#1260] opened 2019-04-23 08:30 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/NationalBankBelgium/stark/blob/master/CONTRIBUTING.md#got-a-question-or-problem
</code></pre>

## Current behavior

When click on the date to edit it: 
  * April 23, 2019 becomes 23/01/2019
  * When edit 23/01/2019 to 23/04/2019, it becomes April 23, 0019

![2019-04-23_10-21-56](https://user-images.githubusercontent.com/10333565/56566007-012fba80-65b2-11e9-802e-b52f623e6724.gif)

## Expected behavior

The date should not be broken by the date mask.

## Minimal reproduction of the problem with instructions

Go in the demo app, in demo-ui > components > date-picker and reproduce the same steps than the one if the video above.

## Environment
<pre><code>
Stark version: 10.0.0-beta.7
</code></pre>

**Comment by christophercr** [comment] 2019-04-30 11:37
After investigating the issue, the problem is due to 2 things:

1. wrong behavior of the mask when deleting characters. The mask moves the rest of the characters backwards/forwards which causes the date picker to get weird date values.
2. the translation initialization logic is not correct. The locale set in Moment is `en-gb` but it should be `en` (US English). This is because the last imported locale sets the current locale (in the Showcase/Starter it was `en-gb`).

Apart from this, we should improve the logic when the application language changes because right now the Moment locale is not changed, which means that the date pickers don't show the date in the current language :(

**Comment by christophercr** [comment] 2019-04-30 11:37
I've created this PR (#1271) for the different fixes

**Comment by christophercr** [comment] 2019-05-14 09:38
The issue about the wrong behavior when deleting characters will be partially fixed in #1271 so we can release soon.

However, this should be completely fixed later on. This will be tracked in #1277

**Closed** 2019-05-14 13:54 UTC
Labels: comp: stark-showcase, comp: stark-starter, comp: stark-ui, type: bug
