### ISSUE TITLE
ui: date-picker - No error/warning when entering manually a wrong date format

### ISSUE THREAD

**Issue by nicanac** [NationalBankBelgium/stark#1353] opened 2019-07-08 13:53 UTC
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/NationalBankBelgium/stark/blob/master/CONTRIBUTING.md#got-a-question-or-problem
</code></pre>

## Current behavior
When entering manually a wrong date format, automatic change without signalling it (no error on invalid date).

Example : Typed manually '20/20/2019', component changed it in 'January 20,2020'.

## Expected behavior
Error message on date format 

## What is the motivation / use case for changing the behavior?
Currently used in Bessy, and having issue with dates in form

## Environment
<pre><code>
Angular version: 7.x
Stark version: 10.0.0-beta.8

Browser:
- [X] Chrome (desktop) version XX
- [X] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [X ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [X] IE version XX
- [X] Edge version XX
 </code></pre>

**Comment by christophercr** [comment] 2019-10-11 12:37
What is the expected behavior actually? To log a warning message in the browser console?

**Comment by nicanac** [comment] 2019-10-11 12:46
no actually it's really specific, when you type manually '20/20/2019, it should warn you it's no a valid date. With a warning like the one we have when entering a date out of the allowed range.
![image](https://user-images.githubusercontent.com/51330762/66652376-e3284600-ec35-11e9-9bb9-706624727d1e.png)

**Comment by christophercr** [comment] 2019-10-11 14:26
I'm afraid is not straightforward to implement a fix for this because we are using the `MomentDateModule` in the StarkDatePicker (see [here](https://github.com/NationalBankBelgium/stark/blob/master/packages/stark-ui/src/modules/date-picker/date-picker.module.ts#L19)). This [`MomentDateModule`](https://github.com/angular/components/blob/master/src/material-moment-adapter/adapter/index.ts#L21) uses the [`MomentDateAdapter`](https://github.com/angular/components/blob/master/src/material-moment-adapter/adapter/moment-date-adapter.ts) that parses the values entered in the field to create a Moment date and viceversa.

This adapter is the one that is automatically converting the '20/20/2019' to ' January 20,2020' m so we cannot display a validation error because there is simply no error.

Not sure how can we solve this without re-implementing the date adapter... any ideas @carlo-nomes, @SuperITMan, @nicanac?

**Comment by carlo-nomes** [comment] 2019-10-16 07:32
In the showcase we have a dateMask on the input, making it impossible to type `20/20/2019` maybe we can do that for the date range picker as well?

**Comment by christophercr** [comment] 2019-10-17 10:46
Oh yeah! Indeed, @nicanac I think you can simply advice to the affected projects to use the dateMask as suggested by @carlo-nomes. That way is impossible to type wrong dates that can be parsed by the `MomentDateAdapter` in an unexpected way.

**Comment by SuperITMan** [comment] 2020-01-08 12:02
@nicanac what is the current status of this ? 😊

**Comment by nicanac** [comment] 2020-01-08 12:06
I've explained the way to work with the dateMask to Dimitri (Bessy). And they're quite happy that :-)

**Comment by SuperITMan** [comment] 2020-01-08 12:14
So can we close this issue? 😊

**Comment by nicanac** [comment] 2020-01-08 12:25
Yes sure :-)

**Closed** 2020-01-08 12:26 UTC
Labels: comp: stark-ui, type: bug
